<?php

########################################################################
# Extension Manager/Repository config file for ext: "edfu"
#
# Auto generated by Extension Builder 2012-11-02
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Edfu',
	'description' => 'Temple of Edfu',
	'category' => 'plugin',
	'author' => 'Ingo Pfennigstorf, Sven-S. Porst',
	'author_email' => 'pfennigstorf@sub.uni-goettingen.de, porst@sub.uni-goettingen.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '4.7',
			'fluid' => '4.7',
			'typo3' => '4.7',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>